### ISSUE TITLE
UI美化

### ISSUE THREAD

**Issue by yaosai** [yhl452493373/DownloadManager#1]
建议下载状态变成完成或失败后不显示进度条，有个进度条感觉怪怪的

**Comment by yhl452493373** [comment]
这个后面看怎么修改了。。木有美工设计，界面就放飞自我了

**Comment by yhl452493373** [comment]
> 这个后面看怎么修改了。。木有美工设计，界面就放飞自我了

目前更新到1.5.6后，下载完或取消下载的项就没有进度条了
