### ISSUE TITLE
下载链接点击后无反应

### ISSUE THREAD

**Issue by yi-Xu-0100** [yhl452493373/DownloadManager#13]
RT，点击后无反应，在预览页面显示为：

![image](https://user-images.githubusercontent.com/25523606/92094957-a1812a80-ee07-11ea-8553-a82c03d5b5dd.png)

在下载界面显示为：

![image](https://user-images.githubusercontent.com/25523606/92094991-aba32900-ee07-11ea-8657-fb33ee5bcc7d.png)

希望接管后，提供弹窗选项。

开始一直以为下载不下来……
**PS，我使用的是edge dev版本，不知道是否与新出现的更新有关。**

**Comment by brucmao** [comment]
chrome同样遇到这个问题了85.0.4183.121
一直是处理中，在这个页面chrome://downloads/ 可以看到需要手动处理，以前都可以直接接管的，难道是因为我升级系统到win 10 2004的原因？
![image](https://user-images.githubusercontent.com/6119652/94634658-3857de80-0303-11eb-94f8-9716e34b727e.png)

**Comment by shuohao** [comment]
升级到最新版86后出现这个问题 期待作者优化

**Comment by yhl452493373** [comment]
> RT，点击后无反应，在预览页面显示为：
> 
> ![image](https://user-images.githubusercontent.com/25523606/92094957-a1812a80-ee07-11ea-8553-a82c03d5b5dd.png)
> 
> 在下载界面显示为：
> 
> ![image](https://user-images.githubusercontent.com/25523606/92094991-aba32900-ee07-11ea-8657-fb33ee5bcc7d.png)
> 
> 希望接管后，提供弹窗选项。
> 
> 开始一直以为下载不下来……
> **PS，我使用的是edge dev版本，不知道是否与新出现的更新有关。**

能否提供一下下载连接用于复现问题？

**Comment by yi-Xu-0100** [comment]
@yhl452493373 任意链接皆可，如 <https://codeload.github.com/yhl452493373/DownloadManager/zip/1.7.7>

![image](https://user-images.githubusercontent.com/25523606/98620635-9df6ac00-2340-11eb-969c-128a28afcb61.png)

![image](https://user-images.githubusercontent.com/25523606/98620672-b2d33f80-2340-11eb-8ee8-7ec13fd306d5.png)

主要是这里的设置，如果是询问的话，则不会有弹窗，而只是在下载界面，造成下载暂停，而如果是不选这些，则直接会被下载，完全没有确认。

**Comment by yhl452493373** [comment]
我去看看

**Comment by yhl452493373** [comment]
> @yhl452493373 任意链接皆可，如 https://codeload.github.com/yhl452493373/DownloadManager/zip/1.7.7
> 
> ![image](https://user-images.githubusercontent.com/25523606/98620635-9df6ac00-2340-11eb-969c-128a28afcb61.png)
> 
> ![image](https://user-images.githubusercontent.com/25523606/98620672-b2d33f80-2340-11eb-8ee8-7ec13fd306d5.png)
> 
> 主要是这里的设置，如果是询问的话，则不会有弹窗，而只是在下载界面，造成下载暂停，而如果是不选这些，则直接会被下载，完全没有确认。

你是用的windows吗？我mac，chrome 86测试没出现这个问题

**Comment by yhl452493373** [comment]
> > @yhl452493373 任意链接皆可，如 https://codeload.github.com/yhl452493373/DownloadManager/zip/1.7.7
> > ![image](https://user-images.githubusercontent.com/25523606/98620635-9df6ac00-2340-11eb-969c-128a28afcb61.png)
> > ![image](https://user-images.githubusercontent.com/25523606/98620672-b2d33f80-2340-11eb-8ee8-7ec13fd306d5.png)
> > 主要是这里的设置，如果是询问的话，则不会有弹窗，而只是在下载界面，造成下载暂停，而如果是不选这些，则直接会被下载，完全没有确认。
> 
> 你是用的windows吗？我mac，chrome 86测试没出现这个问题

另外windows，chrome 86也没出现这问题

**Comment by yi-Xu-0100** [comment]
@yhl452493373 

![image](https://user-images.githubusercontent.com/25523606/98623629-1b251f80-2347-11eb-9113-fb3408ac2d83.png)

**Comment by yi-Xu-0100** [comment]
@yhl452493373 

chrome 中，没有问题，可以弹窗，但是 edge 不行。

![image](https://user-images.githubusercontent.com/25523606/98623936-b0281880-2347-11eb-8bca-636de8bb353b.png)

**Comment by yhl452493373** [comment]
> @yhl452493373
> 
> chrome 中，没有问题，可以弹窗，但是 edge 不行。
> 
> ![image](https://user-images.githubusercontent.com/25523606/98623936-b0281880-2347-11eb-8bca-636de8bb353b.png)

已查明原因：出现这个问题应该都是在edge上，edge把下载前询问保存位置这个功能的弹窗挪到了下载完成后，但是又没有相应的接口给开发者（在微软的开发文档中，edge的开发文档是直接给的chrome的开发文档地址），导致没法进行文件位置选择，进而一直卡在处理中。目前我看edge上其他类似插件的反馈页面，在edge上都有这个问题。解决办法是把 edge://settings/downloads 里面的 每次下载都询问我该做些什么 关掉，目前没找到解决方案。

**Comment by yi-Xu-0100** [comment]
@yhl452493373 好的，感谢！等待后面 edge 给出相关的处理吧
