### ISSUE TITLE
小bug

### ISSUE THREAD

**Issue by VIGAKING** [yhl452493373/DownloadManager#17]
edge浏览器下载一直显示处理中

**Comment by yhl452493373** [comment]
目前已有多人反馈这个问题，能否提供一下下载链接？

**Comment by VIGAKING** [comment]
好像所有下载都是这样
我随便找了个网站&nbsp;https://dl-static.iqiyi.com/hz/IQIYIsetup_z43.exe
点击后没有跳出确认就自动下载了 下载后就一直显示处理中&nbsp;


https://www.zhihu.com/question/427606863&nbsp; 这是知乎上遇到相同问题的人 好像所有同类插件都有这样的问题








这是我的系统版本







------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "yhl452493373/DownloadManager"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年11月10日(星期二) 上午10:34
收件人:&nbsp;"yhl452493373/DownloadManager"<DownloadManager@noreply.github.com&gt;;
抄送:&nbsp;"收下你的梦啊"<1132858439@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [yhl452493373/DownloadManager] 小bug (#17)





 
目前已有多人反馈这个问题，能否提供一下下载链接？

**Comment by yhl452493373** [comment]
> https://dl-static.iqiyi.com/hz/IQIYIsetup_z43.exe

我这里在mac和win都试过了。。。没有复现。win下会出现处理中的情况，但是几秒钟后就好了啊

**Comment by VIGAKING** [comment]
有可能是edge的问题 在Chrome里面都是正常的&nbsp; 其他用户也是一样的问题




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "yhl452493373/DownloadManager"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年11月10日(星期二) 上午10:50
收件人:&nbsp;"yhl452493373/DownloadManager"<DownloadManager@noreply.github.com&gt;;
抄送:&nbsp;"收下你的梦啊"<1132858439@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [yhl452493373/DownloadManager] 小bug (#17)





  
https://dl-static.iqiyi.com/hz/IQIYIsetup_z43.exe
  
我这里在mac和win都试过了。。。没有复现。win下会出现处理中的情况，但是几秒钟后就好了啊

**Comment by yhl452493373** [comment]
> 有可能是edge的问题 在Chrome里面都是正常的&nbsp; 其他用户也是一样的问题
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "yhl452493373/DownloadManager" <notifications@github.com&gt;; 发送时间:&nbsp;2020年11月10日(星期二) 上午10:50 收件人:&nbsp;"yhl452493373/DownloadManager"<DownloadManager@noreply.github.com&gt;; 抄送:&nbsp;"收下你的梦啊"<1132858439@qq.com&gt;;"Author"<author@noreply.github.com&gt;; 主题:&nbsp;Re: [yhl452493373/DownloadManager] 小bug (#17) https://dl-static.iqiyi.com/hz/IQIYIsetup_z43.exe 我这里在mac和win都试过了。。。没有复现。win下会出现处理中的情况，但是几秒钟后就好了啊 — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe.

已查明原因：出现这个问题应该都是在edge上，edge把下载前询问保存位置这个功能的弹窗挪到了下载完成后，但是又没有相应的接口给开发者（在微软的开发文档中，edge的开发文档是直接给的chrome的开发文档地址），导致没法进行文件位置选择，进而一直卡在处理中。目前我看edge上其他类似插件的反馈页面，在edge上都有这个问题。解决办法是把 edge://settings/downloads 里面的 每次下载都询问我该做些什么 关掉，目前没找到解决方案。

**Comment by VIGAKING** [comment]
用心了 哈哈




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "yhl452493373/DownloadManager"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年11月10日(星期二) 中午1:10
收件人:&nbsp;"yhl452493373/DownloadManager"<DownloadManager@noreply.github.com&gt;;
抄送:&nbsp;"收下你的梦啊"<1132858439@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [yhl452493373/DownloadManager] 小bug (#17)





  
有可能是edge的问题 在Chrome里面都是正常的&nbsp; 其他用户也是一样的问题
 …
 ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "yhl452493373/DownloadManager" <notifications@github.com&gt;; 发送时间:&nbsp;2020年11月10日(星期二) 上午10:50 收件人:&nbsp;"yhl452493373/DownloadManager"<DownloadManager@noreply.github.com&gt;; 抄送:&nbsp;"收下你的梦啊"<1132858439@qq.com&gt;;"Author"<author@noreply.github.com&gt;; 主题:&nbsp;Re: [yhl452493373/DownloadManager] 小bug (#17) https://dl-static.iqiyi.com/hz/IQIYIsetup_z43.exe 我这里在mac和win都试过了。。。没有复现。win下会出现处理中的情况，但是几秒钟后就好了啊 — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe.
  
已查明原因：出现这个问题应该都是在edge上，edge把下载前询问保存位置这个功能的弹窗挪到了下载完成后，但是又没有相应的接口给开发者（在微软的开发文档中，edge的开发文档是直接给的chrome的开发文档地址），导致没法进行文件位置选择，进而一直卡在处理中。目前我看edge上其他类似插件的反馈页面，在edge上都有这个问题。解决办法是把 edge://settings/downloads 里面的 每次下载都询问我该做些什么 关掉，目前没找到解决方案。
