### ISSUE TITLE
微软商店里找不到了

### ISSUE THREAD

**Issue by shuohao** [yhl452493373/DownloadManager#19]

**Comment by yhl452493373** [comment]
微软商店很早就找不到了。。。我在重新提交，审核也要一段时间。google商店也是

**Comment by yhl452493373** [comment]
edge商店地址：[下载管理](https://microsoftedge.microsoft.com/addons/detail/%E4%B8%8B%E8%BD%BD%E7%AE%A1%E7%90%86/oljecelfndgchlbkmodifnpodpialkjo)

**Comment by yhl452493373** [comment]
edge商店地址：[下载管理](https://microsoftedge.microsoft.com/addons/detail/%E4%B8%8B%E8%BD%BD%E7%AE%A1%E7%90%86/oljecelfndgchlbkmodifnpodpialkjo)

**Comment by shuohao** [comment]
> edge商店地址：[下载管理](https://microsoftedge.microsoft.com/addons/detail/%E4%B8%8B%E8%BD%BD%E7%AE%A1%E7%90%86/oljecelfndgchlbkmodifnpodpialkjo)

ok
