### ISSUE TITLE
黑色模式

### ISSUE THREAD

**Issue by limuyang2** [yhl452493373/DownloadManager#2]
希望能支持黑色模式，现在都是白色的。

**Comment by yhl452493373** [comment]
这个等后面有空了加。主要现在没时间搞。。

**Comment by yhl452493373** [comment]
另外最好能来个人帮我搞个黑色模式下配色效果。。。

**Comment by yhl452493373** [comment]
现在根据浏览器模式自动切换页面颜色和图标颜色。更新到1.6以后就行了。由于windows没有深色模式，我在mac测试的，感觉还行

**Comment by limuyang2** [comment]
> 现在根据浏览器模式自动切换页面颜色和图标颜色。更新到1.6以后就行了。由于windows没有深色模式，我在mac测试的，感觉还行

我也是用的mac，目前效果感觉不错，配色上建议和Chrome的黑色模式一致：32，33，36
