### ISSUE TITLE
疑似bug…

### ISSUE THREAD

**Issue by Itzamana** [yhl452493373/DownloadManager#22]
![1](https://user-images.githubusercontent.com/20204389/100214020-52501f00-2f4a-11eb-86ec-9fadce94312c.png)

下载完成后的通知，“打开”和“打开目录”这两个按钮点击后无效果…

试了下另一个下载管理器扩展，那两个按钮都是正常的…

我又测试了下老版本，发现只有1.7.7是正常的，从1.8.8开始那两个按钮就失效了…

![2](https://user-images.githubusercontent.com/20204389/100215679-45342f80-2f4c-11eb-81dd-a5406e7125c5.png)

87.0.4280.66 (正式版本) （64 位）

**Comment by yhl452493373** [comment]
我瞅瞅

**Comment by yhl452493373** [comment]
> ![1](https://user-images.githubusercontent.com/20204389/100214020-52501f00-2f4a-11eb-86ec-9fadce94312c.png)
> 
> 下载完成后的通知，“打开”和“打开目录”这两个按钮点击后无效果…
> 
> 试了下另一个下载管理器扩展，那两个按钮都是正常的…
> 
> 我又测试了下老版本，发现只有1.7.7是正常的，从1.8.8开始那两个按钮就失效了…
> 
> ![2](https://user-images.githubusercontent.com/20204389/100215679-45342f80-2f4c-11eb-81dd-a5406e7125c5.png)
> 
> 87.0.4280.66 (正式版本) （64 位）

已修复，chrome商店和edge商店都提交了更新。但是估计chrome商店会更新快些。版本1.10.12修复这个问题

**Comment by Itzamana** [comment]
感谢修复，等更新了~

**Comment by Itzamana** [comment]
> > ![1](https://user-images.githubusercontent.com/20204389/100214020-52501f00-2f4a-11eb-86ec-9fadce94312c.png)
> > 下载完成后的通知，“打开”和“打开目录”这两个按钮点击后无效果…
> > 试了下另一个下载管理器扩展，那两个按钮都是正常的…
> > 我又测试了下老版本，发现只有1.7.7是正常的，从1.8.8开始那两个按钮就失效了…
> > ![2](https://user-images.githubusercontent.com/20204389/100215679-45342f80-2f4c-11eb-81dd-a5406e7125c5.png)
> > 87.0.4280.66 (正式版本) （64 位）
> 
> 已修复，chrome商店和edge商店都提交了更新。但是估计chrome商店会更新快些。版本1.10.12修复这个问题

edge商店居然先更新了，chrome那边没动静…哈哈哈~
