### ISSUE TITLE
下載完成後在圖標上提示

### ISSUE THREAD

**Issue by ted1030** [yhl452493373/DownloadManager#28]
目前下載完成後在圖標上是看不出來的
下載小檔案時，因為瞬間就下載完，看不到下載過程的提示，導致不知道有沒有下載到，還要點擊圖示才知道
打開下載開始的通知的話，還需要手動關閉通知，有點不便
建議可以像百分瀏覽器一樣在圖標上顯示完成的任務計數，用戶點擊圖標後消除數字，正在下載的提示可能改成動畫或是其他符號
或是像火狐一樣下載完成後整個圖標變藍
總之就是希望可以從圖標分辨目前是正在下載或是已下載完成

**Comment by yhl452493373** [comment]
抱歉回复的很晚。不过目前你可以打开下载完成通知，这样每下载完一项，就会通知一次。目前没打算在图标上表现处理。后面如果需求这个功能的多的话再加。
