### ISSUE TITLE
建议：希望接管下载后能给个提示

### ISSUE THREAD

**Issue by Landius** [yhl452493373/DownloadManager#3]
可以设置在当前网页上给个通知吗，经常点了下载按钮但是以为没反应。。。
chrome 现在的通知变成 windows 通知，基本是废了
（Chrome版本 80.0.3970.5（正式版本）dev （64 位））

![image](https://user-images.githubusercontent.com/11910028/69517122-c26e4280-0f8e-11ea-96fb-7fd71dcc64b5.png)

**Comment by Landius** [comment]
目前把 chrome://flags/#enable-native-notifications 改成 disable 可以改回原来的通知。

**Comment by yhl452493373** [comment]
> 目前把 chrome://flags/#enable-native-notifications 改成 disable 可以改回原来的通知。

这个还没有一个很好的方案。因为调用chrome下载API时，不是插件调用chrome下载，而是chrome下载时，触发chrome的下载监听，在插件在这个下载监听里面接管了其下载事件。因此，目前的流程第一步是chrome产生下载事件，如果chrome没有产生下载事件，插件就没法知道在下东西而给提示。如果你有发现其他同类插件能做到你说的这个功能，麻烦把插件地址给我一个，我去瞅瞅它代码，看看实现思路

**Comment by yhl452493373** [comment]
> 可以设置在当前网页上给个通知吗，经常点了下载按钮但是以为没反应。。。
> chrome 现在的通知变成 windows 通知，基本是废了
> （Chrome版本 80.0.3970.5（正式版本）dev （64 位））
> 
> ![image](https://user-images.githubusercontent.com/11910028/69517122-c26e4280-0f8e-11ea-96fb-7fd71dcc64b5.png)

另外如果只是需要在下载开始时，在当前页面增加一个下载通知，这个好办。但是需要考虑到我如果切换到其他页面了，这个通知怎么处理。。。。

**Comment by Landius** [comment]
> 另外如果只是需要在下载开始时，在当前页面增加一个下载通知，这个好办。但是需要考虑到我如果切换到其他页面了，这个通知怎么处理。。。。 

这个确实不好搞🤔
