### ISSUE TITLE
2.0.0偶尔会自动浅色图标变为深色图标

### ISSUE THREAD

**Issue by Itzamana** [yhl452493373/DownloadManager#30]
Chrome 101.0.4951.67 64位
扩展版本2.0.0
设置如下
![image](https://user-images.githubusercontent.com/20204389/169957055-6bef2917-bb19-42e5-a68e-01acd884468c.png)

在开始下载后偶尔会自动变成深色图标，右键进选项后就自动恢复为浅色图标了
我还没有找到100%复现的方法…

**Comment by Itzamana** [comment]
我这的情况似乎是打开浏览器后直接找个东西开始下载，下载完成时图标就会自动变成深色，右键点进选项时就会恢复为我设置的浅色…

**Comment by yhl452493373** [comment]
> 我这的情况似乎是打开浏览器后直接找个东西开始下载，下载完成时图标就会自动变成深色，右键点进选项时就会恢复为我设置的浅色…

你之前是不是安装过？卸载后重新安装再试试呢

**Comment by yhl452493373** [comment]
> 我这的情况似乎是打开浏览器后直接找个东西开始下载，下载完成时图标就会自动变成深色，右键点进选项时就会恢复为我设置的浅色…

我试了几次没有复现。。。

**Comment by Itzamana** [comment]
呃…重新安装了扩展，并且把Chrome升级到102.0.5005.63x64之后，再没有出现过这个问题了…

**Comment by Itzamana** [comment]
又偶发了一次，不过这次我也无法复现了……
目前能确定的有两点，1是更新到2.0.0之后出现这个小bug的，2是不做其他动作，打开chrome之后立刻观察图标颜色，会发现一开始图标是深色的，然后迅速会变成我设置的浅色
不过新版已经去掉了深色判定啊…
会不会是和我的系统比较老（LTSB2016）有关…？
![image](https://user-images.githubusercontent.com/20204389/170529786-fce6c8b0-3d99-455f-9f18-3b9d032a6103.png)
![image](https://user-images.githubusercontent.com/20204389/170529825-f91a5524-9e94-4e54-bc8b-6459c9bce58e.png)

**Comment by yhl452493373** [comment]
> 又偶发了一次，不过这次我也无法复现了…… 目前能确定的有两点，1是更新到2.0.0之后出现这个小bug的，2是不做其他动作，打开chrome之后立刻观察图标颜色，会发现一开始图标是深色的，然后迅速会变成我设置的浅色 不过新版已经去掉了深色判定啊… 会不会是和我的系统比较老（LTSB2016）有关…？ ![image](https://user-images.githubusercontent.com/20204389/170529786-fce6c8b0-3d99-455f-9f18-3b9d032a6103.png) ![image](https://user-images.githubusercontent.com/20204389/170529825-f91a5524-9e94-4e54-bc8b-6459c9bce58e.png)

我尝试处理了，现在提交了更新，等chrome商店更新后你更新扩展再试试。

**Comment by Itzamana** [comment]
好的，商店已经更新了，先用两天看看~
