### ISSUE TITLE
macOS下安装插件后全屏切换闪屏问题

### ISSUE THREAD

**Issue by ImmerTry** [yhl452493373/DownloadManager#31]
操作系统：**MacBook Pro 16** 
CPU: **M1 Pro**
运行系统：**macOS Monterey**
谷歌浏览器版本：101.0.4951.64（正式版本） (arm64) || 102.0.5005.61（正式版本） (arm64)
插件版本：2.0.0

现象：
全屏Chrome后 使用触控板 左右滑动切换软件，在切换浏览器时闪屏！
尝试过卸载Chrome，更新Chrome都不行
最后禁用掉插件后，才恢复正常

**Comment by ImmerTry** [comment]
系统版本：**12.4 (21F79)**

**Comment by ImmerTry** [comment]
录了个视频方便定位：https://image.immertry.top/video%2F%E6%BC%94%E7%A4%BA.mp4

**Comment by yhl452493373** [comment]
> 录了个视频方便定位：https://image.immertry.top/video%2F%E6%BC%94%E7%A4%BA.mp4

我大概知道原因了。。。。是丢失焦点后弹窗执行js来检测是否深色模式造成的。看来只能把这功能放到浏览器启动时执行了

**Comment by yhl452493373** [comment]
> 操作系统：**MacBook Pro 16** CPU: **M1 Pro** 运行系统：**macOS Monterey** 谷歌浏览器版本：101.0.4951.64（正式版本） (arm64) || 102.0.5005.61（正式版本） (arm64) 插件版本：2.0.0
> 
> 现象： 全屏Chrome后 使用触控板 左右滑动切换软件，在切换浏览器时闪屏！ 尝试过卸载Chrome，更新Chrome都不行 最后禁用掉插件后，才恢复正常

你如果要使用，先把插件的图标图标颜色改成深色或者浅色，不要用自动。

**Comment by ImmerTry** [comment]
> > 操作系统：**MacBook Pro 16** CPU：**M1 Pro**运行系统：**macOS Monterey**谷歌浏览器版本：101.0.4951.64（正式版本） (arm64) || 102.0.5005.61（正式版本） (arm64) 插件版本：2.0.0
> > 全屏显示后浏览插件，显示在屏幕上滑动屏幕后切换，才过软件切换器测试Chrome，更新后没有行终止禁用正常的Chrome浏览器
> 
> 你如果使用，先把图标的颜色改成插件或者浅色，不要用自动。

好的 我试试

**Comment by ImmerTry** [comment]
> > 操作系统：**MacBook Pro 16** CPU: **M1 Pro** 运行系统：**macOS Monterey** 谷歌浏览器版本：101.0.4951.64（正式版本） (arm64) || 102.0.5005.61（正式版本） (arm64) 插件版本：2.0.0
> > 现象： 全屏Chrome后 使用触控板 左右滑动切换软件，在切换浏览器时闪屏！ 尝试过卸载Chrome，更新Chrome都不行 最后禁用掉插件后，才恢复正常
> 
> 你如果要使用，先把插件的图标图标颜色改成深色或者浅色，不要用自动。

改成浅色来回切换么有问题了

**Comment by yhl452493373** [comment]
> > > 操作系统：**MacBook Pro 16** CPU: **M1 Pro** 运行系统：**macOS Monterey** 谷歌浏览器版本：101.0.4951.64（正式版本） (arm64) || 102.0.5005.61（正式版本） (arm64) 插件版本：2.0.0
> > > 现象： 全屏Chrome后 使用触控板 左右滑动切换软件，在切换浏览器时闪屏！ 尝试过卸载Chrome，更新Chrome都不行 最后禁用掉插件后，才恢复正常
> > 
> > 
> > 你如果要使用，先把插件的图标图标颜色改成深色或者浅色，不要用自动。
> 
> 改成浅色来回切换么有问题了

这东西主要就是chrome在Manifest  V3里面限制了不能直接调用HTML的对象，没法直接在后台执行js。。。必须弹出一个窗口来执行，执行完毕后再关闭。。。反正就是个大坑。windows下我直接把自动改变图标颜色禁用了。mac上测试的时候没测试全屏切换，所以当时没发现这问题

**Comment by ImmerTry** [comment]
> > > > 操作系统：**MacBook Pro 16** CPU: **M1 Pro** 运行系统：**macOS Monterey** 谷歌浏览器版本：101.0.4951.64（正式版本） (arm64) || 102.0.5005.61（正式版本） (arm64) 插件版本：2.0.0
> > > > 现象： 全屏Chrome后 使用触控板 左右滑动切换软件，在切换浏览器时闪屏！ 尝试过卸载Chrome，更新Chrome都不行 最后禁用掉插件后，才恢复正常
> > > 
> > > 
> > > 你如果要使用，先把插件的图标图标颜色改成深色或者浅色，不要用自动。
> > 
> > 
> > 改成浅色来回切换么有问题了
> 
> 这东西主要就是chrome在Manifest V3里面限制了不能直接调用HTML的对象，没法直接在后台执行js。。。必须弹出一个窗口来执行，执行完毕后再关闭。。。反正就是个大坑。windows下我直接把自动改变图标颜色禁用了。mac上测试的时候没测试全屏切换，所以当时没发现这问题

我说呢，Windows怎么没事，可以，极速解决bug(doge)

**Comment by yhl452493373** [comment]
> > > > > 操作系统：**MacBook Pro 16** CPU: **M1 Pro** 运行系统：**macOS Monterey** 谷歌浏览器版本：101.0.4951.64（正式版本） (arm64) || 102.0.5005.61（正式版本） (arm64) 插件版本：2.0.0
> > > > > 现象： 全屏Chrome后 使用触控板 左右滑动切换软件，在切换浏览器时闪屏！ 尝试过卸载Chrome，更新Chrome都不行 最后禁用掉插件后，才恢复正常
> > > > 
> > > > 
> > > > 你如果要使用，先把插件的图标图标颜色改成深色或者浅色，不要用自动。
> > > 
> > > 
> > > 改成浅色来回切换么有问题了
> > 
> > 
> > 这东西主要就是chrome在Manifest V3里面限制了不能直接调用HTML的对象，没法直接在后台执行js。。。必须弹出一个窗口来执行，执行完毕后再关闭。。。反正就是个大坑。windows下我直接把自动改变图标颜色禁用了。mac上测试的时候没测试全屏切换，所以当时没发现这问题
> 
> 我说呢，Windows怎么没事，可以，极速解决bug(doge)

chrome商店提交了更新，等后面更新过后版本2.0.1，你再试试。现在把逻辑调整了。非全屏下浏览器焦点改变就检测一次主题模式，全屏下切换tab的时候检测。默认的主页，chrome://这种tab页面没法检测

**Comment by ImmerTry** [comment]
> > > > > > 操作系统：**MacBook Pro 16** CPU: **M1 Pro** 运行系统：**macOS Monterey** 谷歌浏览器版本：101.0.4951.64（正式版本） (arm64) || 102.0.5005.61（正式版本） (arm64) 插件版本：2.0.0
> > > > > > 现象： 全屏Chrome后 使用触控板 左右滑动切换软件，在切换浏览器时闪屏！ 尝试过卸载Chrome，更新Chrome都不行 最后禁用掉插件后，才恢复正常
> > > > > 
> > > > > 
> > > > > 你如果要使用，先把插件的图标图标颜色改成深色或者浅色，不要用自动。
> > > > 
> > > > 
> > > > 改成浅色来回切换么有问题了
> > > 
> > > 
> > > 这东西主要就是chrome在Manifest V3里面限制了不能直接调用HTML的对象，没法直接在后台执行js。。。必须弹出一个窗口来执行，执行完毕后再关闭。。。反正就是个大坑。windows下我直接把自动改变图标颜色禁用了。mac上测试的时候没测试全屏切换，所以当时没发现这问题
> > 
> > 
> > 我说呢，Windows怎么没事，可以，极速解决bug(doge)
> 
> chrome商店提交了更新，等后面更新过后版本2.0.1，你再试试。现在把逻辑调整了。非全屏下浏览器焦点改变就检测一次主题模式，全屏下切换tab的时候检测。默认的主页，chrome://这种tab页面没法检测

好的 辛苦了

**Comment by yhl452493373** [comment]
我简单测试下，没这问题了

**Comment by ImmerTry** [comment]
> 我简单测试下，没这问题了

嗯 可以了
