### ISSUE TITLE
下载管理（2.0.1版本）没有接管下载

### ISSUE THREAD

**Issue by qinxs** [yhl452493373/DownloadManager#32]
以前正常，5月31日升级后 就是跳出浏览器自己的下载了

浏览器：
Chromium
版本 96.0.4664.93（正式版本） （64 位）

测试链接：
https://qinxs.lanzouh.com/iMfAJp3e8lg

![](https://s3.bmp.ovh/imgs/2022/06/01/01a322107a2b7949.png)

**Comment by yhl452493373** [comment]
我后面找个时间看看

**Comment by yhl452493373** [comment]
只是这个链接是吧

**Comment by yhl452493373** [comment]
> 以前正常，5月31日升级后 就是跳出浏览器自己的下载了
> 
> 浏览器： Chromium 版本 96.0.4664.93（正式版本） （64 位）
> 
> 测试链接： https://qinxs.lanzouh.com/iMfAJp3e8lg
> 
> ![](https://camo.githubusercontent.com/4321de9d9d991b693e86c7c86b437948fcd462b9577412e867177d1fe4c87854/68747470733a2f2f73332e626d702e6f76682f696d67732f323032322f30362f30312f303161333232313037613262373934392e706e67)

暂时你可以先试试卸载后重装。有可能是新版和旧版的设置不兼容引起的

**Comment by yhl452493373** [comment]
> https://qinxs.lanzouh.com/iMfAJp3e8lg

奥，我刚刚在我机器上试了下，这个版本是有这个问题。但是我更新到最新后就可以了。你可以升级下浏览器再试试。

**Comment by qinxs** [comment]
> > https://qinxs.lanzouh.com/iMfAJp3e8lg
> 
> 奥，我刚刚在我机器上试了下，这个版本是有这个问题。但是我更新到最新后就可以了。你可以升级下浏览器再试试。

暂时用回了v1.11.14 空了我自己研究下代码~

**Comment by qinxs** [comment]
用了其他版本Chromium 功能正常
