### ISSUE TITLE
一个小建议…

### ISSUE THREAD

**Issue by Itzamana** [yhl452493373/DownloadManager#4]
感谢发布扩展，很好用，什么都好，就是有一点…
可否在选项里添加一项：在图标下方显示下载进度
就是在图标箭头下面用一个进度条来替代显示数字…
就像这个( https://chrome.google.com/webstore/detail/download-manager/daoidaoebhfcgccdpgjjcbdginkofmfe )的图标那样，这个是我之前在用的，现在已经不用了，因为很久没更新了也不支持深色…

**Comment by yhl452493373** [comment]
后面再看吧。。最近忙着准备结婚呢。。。

**Comment by Itzamana** [comment]
> 后面再看吧。。最近忙着准备结婚呢。。。

恭喜呀~

**Comment by yhl452493373** [comment]
你给的连接失效了。。。

**Comment by Itzamana** [comment]
好像是诶…说起来这个项目主页的链接也失效了…呃…
其实就是在图标上不用显示正在下载文件的数量，而显示一个目前下载的进度条就行…或者有一个选项可以切换这两种显示内容…

**Comment by Itzamana** [comment]
之前那个例子找不到了…只找到了这个：https://github.com/xinghaix/download-manager
不过他是把下载进度直接做在箭头的图标上了，看着不是很清楚，而且资源占用略大…

**Comment by yhl452493373** [comment]
edge商店地址：[下载管理](https://microsoftedge.microsoft.com/addons/detail/%E4%B8%8B%E8%BD%BD%E7%AE%A1%E7%90%86/oljecelfndgchlbkmodifnpodpialkjo)

chrome商店一直不给通过。。

**Comment by yhl452493373** [comment]
另外你给我那个我从其截图上看似乎没有在图标上显示下载进度的功能

**Comment by Itzamana** [comment]
> 另外你给我那个我从其截图上看似乎没有在图标上显示下载进度的功能

他那个截图应该是挺久前的了…现在是有的，并且还能自定义图标的进度颜色，只不过他那个图标比较小，所以效果在我看来并不理想…
我还是比较喜欢正常的进度条…

**Comment by Itzamana** [comment]
> 另外你给我那个我从其截图上看似乎没有在图标上显示下载进度的功能

终于上架Chrome商店了，恭喜大哥~
现在下载中也可以看到图标变色了，赞！
话说大哥还打算添加“在图标上显示下载进度条”这个功能吗…？

**Comment by yhl452493373** [comment]
> > 另外你给我那个我从其截图上看似乎没有在图标上显示下载进度的功能
> 
> 终于上架Chrome商店了，恭喜大哥~
> 现在下载中也可以看到图标变色了，赞！
> 话说大哥还打算添加“在图标上显示下载进度条”这个功能吗…？

等我研究下看看

**Comment by Itzamana** [comment]
感谢更新，已经看到图标显示进度功能了~~
虽然和想象中的不太一样…
虽然感觉挺厚脸皮的…但还是说一下我最开始建立这个反馈时的想法吧…
![无标题](https://user-images.githubusercontent.com/20204389/99965355-b7cbd080-2dcf-11eb-8c11-267e02844ff4.png)

**Comment by Itzamana** [comment]
不过现在这样已经比较满足了，再次感谢！

**Comment by yhl452493373** [comment]
> 不过现在这样已经比较满足了，再次感谢！

主要是svg绘图我不熟，就用的两个图标，比较简单。。。
