### ISSUE TITLE
希望上架到edge商店啊啊啊！！！！！

### ISSUE THREAD

**Issue by TusiCharles** [yhl452493373/DownloadManager#8]

**Comment by yhl452493373** [comment]
已提交，审核中。。。届时我会把chrome和edge的连接都加到readme

**Comment by yhl452493373** [comment]
edge商店地址：[下载管理](https://microsoftedge.microsoft.com/addons/detail/%E4%B8%8B%E8%BD%BD%E7%AE%A1%E7%90%86/oljecelfndgchlbkmodifnpodpialkjo)

**Comment by Itzamana** [comment]
Chrome商店还没上架么…

**Comment by yhl452493373** [comment]
> Chrome商店还没上架么…

刚通过，上了。
