### ISSUE TITLE
对于下载失败的处理有问题和一点小建议

### ISSUE THREAD

**Issue by fjqingyou** [yhl452493373/DownloadManager#9]
# Bug
顶部插件图标点开的界面中，对下载失败的任务点击代表继续下载的三角形按钮。无效。。

# 建议
>1、期待加入自动重试功能。例如可以针对容易失败的网站添加自动重试N次的功能。

>2、上方提案可行的话，期望有流量变化自动重置次数记录功能开关

**Comment by fjqingyou** [comment]
环境： 
Win10 x64
Google Chrome
版本 81.0.4044.113（正式版本） （64 位）

**Comment by yhl452493373** [comment]
这个只接管浏览器功能，不做其他操作哈。浏览器下载失败了不会自动重下，这个就不会自动重下。
